### ISSUE TITLE
Windows support (TypeError: Cannot write to hid device)

### ISSUE THREAD

**Issue by HEllRZA** [timrogers/litra-glow#24]
Hi! Thanx for this project!
I an into an issue on Windows (11)

```shell
$ litra-on.cmd
TypeError: Cannot write to hid device
    at turnOn (C:\Users\UserName\AppData\Roaming\npm\node_modules\litra-glow\dist\commonjs\driver.js:28:12)
    at Object.<anonymous> (C:\Users\UserName\AppData\Roaming\npm\node_modules\litra-glow\dist\commonjs\cli\litra-on.js:7:25)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```
The problem is that there are actually two HID devices found:
```yaml
# console.log(HID.devices());
{
  {
    vendorId: 1133,
    productId: 51456,
    path: '\\\\?\\hid#vid_046d&pid_c900&col01#6&21f11cb5&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: '',
    manufacturer: '',
    product: '',
    release: 256,
    interface: -1,
    usagePage: 12,
    usage: 1
  },
  {
    vendorId: 1133,
    productId: 51456,
    path: '\\\\?\\hid#vid_046d&pid_c900&col02#6&21f11cb5&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: '',
    manufacturer: '',
    product: '',
    release: 256,
    interface: -1,
    usagePage: 65347,
    usage: 514
  }
}
```

And the current implementation selects the first of them, which does not work.
The second one actually works.

This code snippet gets the correct device, by additionally checking the `usagePage`; this has to be tested on MacOS though.
```typescript
const USAGE_PAGE = 0xff43;
const devices = HID.devices();
const deviceInfo = devices.find(function (d: any) {
  return (
    d.vendorId === VENDOR_ID &&
    d.productId === PRODUCT_ID &&
    d.usagePage === USAGE_PAGE
  );
});
if (deviceInfo) {
  const device = new HID.HID(deviceInfo.path);
  turnOn(device);
} else {
  console.log('No Litra Glow device found');
}
```

Verify if the new code works on different Operating systems
- [x] Windows 11
- [x] MacOS 11.7.1
- [x] Ubuntu 16.04 (via Parallels)

## Ubuntu
I had troubles with the udev rule from [go-litra-driver](https://github.com/derickr/go-litra-driver).
But this works for me:
`/etc/udev/rules.d/82-litra-glow.rules`
```ini
# Litra Glow 
ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c900", GROUP="plugdev", MODE="0664"
```
